### ISSUE TITLE
nuxt vuetify module error

### ISSUE THREAD

**Issue by kingdomac** [invictus-codes/nuxt-vuetify#15]
### Contact Details

mac.cheaib@gmail.com

### What happened?

After running 
npm install --save-dev @invictus.codes/nuxt-vuetify

and adding @invictus.codes/nuxt-vuetify to the modules section of nuxt.config.ts as in the documentation i got this error when running:

npm run dev

 

### Version

1.0.2 (Default)

### Relevant log output

```shell
ERROR  Cannot restart nuxt:  string is not defined

  at C:/projects/nuxt/nuxt-app/nuxt.config.ts:17:65
  at Object.jiti (node_modules\jiti\dist\jiti.js:1:245784)
  at resolveConfig (/C:/projects/nuxt/nuxt-app/node_modules/c12/dist/index.mjs:279:24)
  at loadConfig (/C:/projects/nuxt/nuxt-app/node_modules/c12/dist/index.mjs:116:40)
  at async loadNuxtConfig (/C:/projects/nuxt/nuxt-app/node_modules/@nuxt/kit/dist/index.mjs:480:18)
  at async loadNuxt (/C:/projects/nuxt/nuxt-app/node_modules/nuxt/dist/index.mjs:2939:19)
  at async loadNuxt (/C:/projects/nuxt/nuxt-app/node_modules/@nuxt/kit/dist/index.mjs:534:19)
  at async load (/C:/projects/nuxt/nuxt-app/node_modules/nuxi/dist/chunks/dev.mjs:182:23)
  at async _applyPromised (/C:/projects/nuxt/nuxt-app/node_modules/nuxi/dist/chunks/dev.mjs:96:10)
```

**Comment by ascorbic-acid** [comment]
you must select one option, for example

change: styles: true | 'none' | 'expose' | 'sass' | { configFile: string },
to one of the options for example: styles: true,

**Comment by jvhellemondt** [comment]
Could you provide a codepen/ codesandbox with your setup? So we can check your settings?

**Comment by thomassittig** [comment]
fyi: i ran in the same situation. i would recommend to update the documentation to be a bit more clear. providing a invalid configuration as an copy/paste example is misleading in my opinion.

As the options are described directly after the example, the sample does not really need them.
