### ISSUE TITLE
[Bug]: Component <component-name> is missing template or render function

### ISSUE THREAD

**Issue by rkfiv** [invictus-codes/nuxt-vuetify#22]
### Contact Details

robert@immify.net

### What happened?

[Vue warn]: Component VAppBar is missing template or render function.   

### Version

1.0.2 (Default)

**Comment by imduchy** [comment]
I'm seeing the same issue with `VAppBar` and `VNavigationDrawer`

**Comment by jvhellemondt** [comment]
Could you provide a codepen/ codesandbox with your code? Can't really tell what's happening with only the error message

**Comment by JeppePepp** [comment]
When trying to use VAppBar

[Vuetify] Could not find injected layout

at Object.setup [as _setup] (C:\GIT\dev\laundrop.lastest.nuxt\node_modules\vuetify\lib\components\VAppBar\VAppBar.mjs:112:31)
at setup (C:\GIT\dev\laundrop.lastest.nuxt\node_modules\vuetify\lib\util\defineComponent.mjs:30:43)
at callWithErrorHandling (C:\GIT\dev\laundrop.lastest.nuxt\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:156:18)
at setupStatefulComponent (C:\GIT\dev\laundrop.lastest.nuxt\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7190:25)
at setupComponent (C:\GIT\dev\laundrop.lastest.nuxt\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7151:36)
at renderComponentVNode (C:\GIT\dev\laundrop.lastest.nuxt\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:614:15)
at Module.ssrRenderComponent (C:\GIT\dev\laundrop.lastest.nuxt\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:86:10)
at _sfc_ssrRender (C:\GIT\dev\laundrop.lastest.nuxt\components\AppHeader.js:30:31)
at renderComponentSubTree (C:\GIT\dev\laundrop.lastest.nuxt\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:683:9)

**Comment by lokinz** [comment]
You need to have `v-app-bar` inside of a `v-app`.
